/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminConfigRouteImport } from './routes/_authenticated/admin-config'
import { Route as ApiPiConfigRouteImport } from './routes/api/pi-config'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiAuthPiRouteImport } from './routes/api/auth.pi'
import { Route as ApiPublicRatesRouteImport } from './routes/api/public/rates'
import { Route as ApiPublicRewardsConfigRouteImport } from './routes/api/public/rewards-config'
import { Route as ApiPublicPiApproveRouteImport } from './routes/api/public/pi/approve'
import { Route as ApiPublicPiCompleteRouteImport } from './routes/api/public/pi/complete'
import { Route as ApiPublicPiIncompleteRouteImport } from './routes/api/public/pi/incomplete'
import { Route as ApiPublicPiReconcileRouteImport } from './routes/api/public/pi/reconcile'
import { Route as ApiPublicPiRewardsRouteImport } from './routes/api/public/pi/rewards'
import { Route as ApiPublicPiStatusRouteImport } from './routes/api/public/pi/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminConfigRoute =
  AuthenticatedAdminConfigRouteImport.update({
    id: '/admin-config',
    path: '/admin-config',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPiConfigRoute = ApiPiConfigRouteImport.update({
  id: '/api/pi-config',
  path: '/api/pi-config',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthPiRoute = ApiAuthPiRouteImport.update({
  id: '/api/auth/pi',
  path: '/api/auth/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRatesRoute = ApiPublicRatesRouteImport.update({
  id: '/api/public/rates',
  path: '/api/public/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRewardsConfigRoute = ApiPublicRewardsConfigRouteImport.update({
  id: '/api/public/rewards-config',
  path: '/api/public/rewards-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiApproveRoute = ApiPublicPiApproveRouteImport.update({
  id: '/api/public/pi/approve',
  path: '/api/public/pi/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCompleteRoute = ApiPublicPiCompleteRouteImport.update({
  id: '/api/public/pi/complete',
  path: '/api/public/pi/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiIncompleteRoute = ApiPublicPiIncompleteRouteImport.update({
  id: '/api/public/pi/incomplete',
  path: '/api/public/pi/incomplete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiReconcileRoute = ApiPublicPiReconcileRouteImport.update({
  id: '/api/public/pi/reconcile',
  path: '/api/public/pi/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiRewardsRoute = ApiPublicPiRewardsRouteImport.update({
  id: '/api/public/pi/rewards',
  path: '/api/public/pi/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiStatusRoute = ApiPublicPiStatusRouteImport.update({
  id: '/api/public/pi/status',
  path: '/api/public/pi/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/entertainment': typeof EntertainmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-config': typeof AuthenticatedAdminConfigRoute
  '/api/pi-config': typeof ApiPiConfigRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/pi': typeof ApiAuthPiRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/rewards-config': typeof ApiPublicRewardsConfigRoute
  '/api/public/pi/approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi/complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi/incomplete': typeof ApiPublicPiIncompleteRoute
  '/api/public/pi/reconcile': typeof ApiPublicPiReconcileRoute
  '/api/public/pi/rewards': typeof ApiPublicPiRewardsRoute
  '/api/public/pi/status': typeof ApiPublicPiStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/entertainment': typeof EntertainmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-config': typeof AuthenticatedAdminConfigRoute
  '/api/pi-config': typeof ApiPiConfigRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/pi': typeof ApiAuthPiRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/rewards-config': typeof ApiPublicRewardsConfigRoute
  '/api/public/pi/approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi/complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi/incomplete': typeof ApiPublicPiIncompleteRoute
  '/api/public/pi/reconcile': typeof ApiPublicPiReconcileRoute
  '/api/public/pi/rewards': typeof ApiPublicPiRewardsRoute
  '/api/public/pi/status': typeof ApiPublicPiStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkin': typeof CheckinRoute
  '/community': typeof CommunityRoute
  '/entertainment': typeof EntertainmentRoute
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/notifications': typeof NotificationsRoute
  '/premium': typeof PremiumRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-config': typeof AuthenticatedAdminConfigRoute
  '/api/pi-config': typeof ApiPiConfigRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/pi': typeof ApiAuthPiRoute
  '/api/public/rates': typeof ApiPublicRatesRoute
  '/api/public/rewards-config': typeof ApiPublicRewardsConfigRoute
  '/api/public/pi/approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi/complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi/incomplete': typeof ApiPublicPiIncompleteRoute
  '/api/public/pi/reconcile': typeof ApiPublicPiReconcileRoute
  '/api/public/pi/rewards': typeof ApiPublicPiRewardsRoute
  '/api/public/pi/status': typeof ApiPublicPiStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/entertainment'
    | '/marketplace'
    | '/mcp'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/admin-config'
    | '/api/pi-config'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/pi'
    | '/api/public/rates'
    | '/api/public/rewards-config'
    | '/api/public/pi/approve'
    | '/api/public/pi/complete'
    | '/api/public/pi/incomplete'
    | '/api/public/pi/reconcile'
    | '/api/public/pi/rewards'
    | '/api/public/pi/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/entertainment'
    | '/marketplace'
    | '/mcp'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/admin-config'
    | '/api/pi-config'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/pi'
    | '/api/public/rates'
    | '/api/public/rewards-config'
    | '/api/public/pi/approve'
    | '/api/public/pi/complete'
    | '/api/public/pi/incomplete'
    | '/api/public/pi/reconcile'
    | '/api/public/pi/rewards'
    | '/api/public/pi/status'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkin'
    | '/community'
    | '/entertainment'
    | '/marketplace'
    | '/mcp'
    | '/notifications'
    | '/premium'
    | '/privacy'
    | '/profile'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/admin-config'
    | '/api/pi-config'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/pi'
    | '/api/public/rates'
    | '/api/public/rewards-config'
    | '/api/public/pi/approve'
    | '/api/public/pi/complete'
    | '/api/public/pi/incomplete'
    | '/api/public/pi/reconcile'
    | '/api/public/pi/rewards'
    | '/api/public/pi/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckinRoute: typeof CheckinRoute
  CommunityRoute: typeof CommunityRoute
  EntertainmentRoute: typeof EntertainmentRoute
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  NotificationsRoute: typeof NotificationsRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  StakingRoute: typeof StakingRoute
  SwapRoute: typeof SwapRoute
  TermsRoute: typeof TermsRoute
  WalletRoute: typeof WalletRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiPiConfigRoute: typeof ApiPiConfigRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAuthPiRoute: typeof ApiAuthPiRoute
  ApiPublicRatesRoute: typeof ApiPublicRatesRoute
  ApiPublicRewardsConfigRoute: typeof ApiPublicRewardsConfigRoute
  ApiPublicPiApproveRoute: typeof ApiPublicPiApproveRoute
  ApiPublicPiCompleteRoute: typeof ApiPublicPiCompleteRoute
  ApiPublicPiIncompleteRoute: typeof ApiPublicPiIncompleteRoute
  ApiPublicPiReconcileRoute: typeof ApiPublicPiReconcileRoute
  ApiPublicPiRewardsRoute: typeof ApiPublicPiRewardsRoute
  ApiPublicPiStatusRoute: typeof ApiPublicPiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-config': {
      id: '/_authenticated/admin-config'
      path: '/admin-config'
      fullPath: '/admin-config'
      preLoaderRoute: typeof AuthenticatedAdminConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/pi-config': {
      id: '/api/pi-config'
      path: '/api/pi-config'
      fullPath: '/api/pi-config'
      preLoaderRoute: typeof ApiPiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/pi': {
      id: '/api/auth/pi'
      path: '/api/auth/pi'
      fullPath: '/api/auth/pi'
      preLoaderRoute: typeof ApiAuthPiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rates': {
      id: '/api/public/rates'
      path: '/api/public/rates'
      fullPath: '/api/public/rates'
      preLoaderRoute: typeof ApiPublicRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rewards-config': {
      id: '/api/public/rewards-config'
      path: '/api/public/rewards-config'
      fullPath: '/api/public/rewards-config'
      preLoaderRoute: typeof ApiPublicRewardsConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/approve': {
      id: '/api/public/pi/approve'
      path: '/api/public/pi/approve'
      fullPath: '/api/public/pi/approve'
      preLoaderRoute: typeof ApiPublicPiApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/complete': {
      id: '/api/public/pi/complete'
      path: '/api/public/pi/complete'
      fullPath: '/api/public/pi/complete'
      preLoaderRoute: typeof ApiPublicPiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/incomplete': {
      id: '/api/public/pi/incomplete'
      path: '/api/public/pi/incomplete'
      fullPath: '/api/public/pi/incomplete'
      preLoaderRoute: typeof ApiPublicPiIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/reconcile': {
      id: '/api/public/pi/reconcile'
      path: '/api/public/pi/reconcile'
      fullPath: '/api/public/pi/reconcile'
      preLoaderRoute: typeof ApiPublicPiReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/rewards': {
      id: '/api/public/pi/rewards'
      path: '/api/public/pi/rewards'
      fullPath: '/api/public/pi/rewards'
      preLoaderRoute: typeof ApiPublicPiRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi/status': {
      id: '/api/public/pi/status'
      path: '/api/public/pi/status'
      fullPath: '/api/public/pi/status'
      preLoaderRoute: typeof ApiPublicPiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminConfigRoute: typeof AuthenticatedAdminConfigRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminConfigRoute: AuthenticatedAdminConfigRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckinRoute: CheckinRoute,
  CommunityRoute: CommunityRoute,
  EntertainmentRoute: EntertainmentRoute,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  NotificationsRoute: NotificationsRoute,
  PremiumRoute: PremiumRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  StakingRoute: StakingRoute,
  SwapRoute: SwapRoute,
  TermsRoute: TermsRoute,
  WalletRoute: WalletRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiPiConfigRoute: ApiPiConfigRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAuthPiRoute: ApiAuthPiRoute,
  ApiPublicRatesRoute: ApiPublicRatesRoute,
  ApiPublicRewardsConfigRoute: ApiPublicRewardsConfigRoute,
  ApiPublicPiApproveRoute: ApiPublicPiApproveRoute,
  ApiPublicPiCompleteRoute: ApiPublicPiCompleteRoute,
  ApiPublicPiIncompleteRoute: ApiPublicPiIncompleteRoute,
  ApiPublicPiReconcileRoute: ApiPublicPiReconcileRoute,
  ApiPublicPiRewardsRoute: ApiPublicPiRewardsRoute,
  ApiPublicPiStatusRoute: ApiPublicPiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
